Adicionando artigo do algoritmo de Shor
qcomp-eld/qcomp-eld.github.io pull request #11
Opened 2022-12-08 16:37 UTC by luccasmarim

2022-12-08 18:10 UTC, alissonfumaco requested changes
Tu criou uma entrada no `_config.yml` pro teu usuário?

2022-12-14 11:54 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +Antes de começar, introduziremos alguns conceitos importantes para a construção dessa rotina. Estes são: Transformada de Fourier quântica, aritmética modular, algoritmo de Euclides e de frações conti
```suggestion
Antes de começar, introduziremos alguns conceitos importantes para a construção dessa rotina. Estes são: Transformada de Fourier quântica, aritmética modular, algoritmo de Euclides e de frações continuadas. Outras ferramentas importantes para simplificar o algoritmo estarão disponiveis na seção de apêndices.
```

Não seria apêndices?

2022-12-14 12:45 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +qc = QuantumCircuit(3)
Penso que podemos marcar esse trecho de código como um bloco de código, de forma que isso fique visivel ao texto. Podemos fazer isso com a adição de highlight para a sintaxe, no próprio markdown, inserindo essa parte do script dentro de um bloco iniciado por: " ``` python " e finalizado por " ``` ".

2022-12-14 12:55 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +Pode-se definir (ref. I) operações de adição e multiplicação nesse conjunto de forma que $$ Z_n = \overline{0}, \overline{1}, ..., \overline{n-1} $$ seja um grupo. A adição pode ser tal que $$ \overl
```suggestion
Pode-se definir (ref. I) operações de adição e multiplicação nesse conjunto de forma que $$ Z_n = \overline{0}, \overline{1}, ..., \overline{n-1} $$ seja um grupo. A adição pode ser tal que $$ \overline{a}+\overline{b}= \overline{a+b} $$ e a multiplicação, não obstante, pode ser $$ \overline{a}*\overline{b}= \overline{a*b} $$. Note que é extremamente conveniente a forma que definimos essas operações. De fato, para somar ou multiplicar os elementos do grupo basta somar e multiplicar da forma usual e os elementos neutros serão os usuais.
```

Penso que ali seria "basta", não?

2022-12-14 13:02 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +Outra notação mais importante ainda é a de $$ A (mod N) $$. Esta representa o resto da divisão de A por N (em Python usamos: A%N)
```suggestion
Outra notação mais importante ainda é a de $$ A (mod N) $$. Esta representa o resto da divisão de A por N (em Python usamos: A%N).
```

2022-12-14 13:06 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +Nesta notação, a ordem ou período de um número inteiro A é o menor inteiro $$ r $$ tal que $$ A^r(modN)=1 $$
```suggestion
Nesta notação, a ordem ou período de um número inteiro A é o menor inteiro $$ r $$ tal que $$ A^r(modN)=1 $$.
```

2022-12-14 13:41 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +Enfim realizamos a medição na base computacional. Obtendo $$ \ket{0} $$ quando k=0 não teremos informação sobre o sistema mas se o resultado da medição for $$ \ket{\frac{k_12^t}{r}} $$ por algum $$ k
```suggestion
Enfim, realizamos a medição na base computacional. Obtendo $$ \ket{0} $$ quando k=0 não teremos informação sobre o sistema, mas, se o resultado da medição for $$ \ket{\frac{k_12^t}{r}} $$ por algum $$ k_1>0 $$, dividimos por $$ 2^t $$ e teremos duas possibilidades: MDC(k,r)=1 ou MDC(k,r) é diferente de 1. No primeiro caso fazemos $$ x^r = 1 mod N $$ e temos a ordem. No segundo caso o denominador será um d, que é um fator de r e nesse caso o algoritmo falha.
```

2022-12-14 13:44 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +com $$ \ket{c}\in \ket{0}, \ket{1},..., \ket{2^t-1} $$ e $$ \ket{\alpha_c} $$ vem da decomposição de $$ \ket{\psi_3} $$ em relação à base computacional do primeiro registrador.
```suggestion
Com $$ \ket{c}\in \ket{0}, \ket{1},..., \ket{2^t-1} $$ e $$ \ket{\alpha_c} $$ vindo da decomposição de $$ \ket{\psi_3} $$ em relação à base computacional do primeiro registrador. 
```

2022-12-14 13:47 UTC, fecaletti commented on _posts/2022-11-21-shor-algorithm.md
> +onde $$ \alpha = \frac{q-\beta}{r} $$ com sendo o resto da divisão de q por r.
```suggestion
onde $$ \alpha = \frac{q-\beta}{r} $$ sendo o resto da divisão de q por r.
```

2022-12-16 18:07 UTC, closed without merging