Add post about bell states and quantum teleportation
qcomp-eld/qcomp-eld.github.io pull request #9
Opened 2022-09-13 23:29 UTC by alissonfumaco

2022-09-26 20:03 UTC, qcomp-eld requested changes

2022-09-26 20:15 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +A mecanica quântica começou a ganhar rapidamente defensodres durante o século 20. Tão rápido quanto os seus seguidores, surgiram os seus críticios.
Corrigido, obrigado!

2022-09-26 20:15 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Um dos críticos mais famosos da mecanica quântica foi Albert Einstein. Um de seus alunos de doutorado Podolsky publicou em 1935 - tendo Einstein e Rosen como co-autores - o artigo _Can Quantum-Mechan
Corrigido, obrigado!

2022-09-26 20:15 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Os bell states foram apresentados em 1964 por John Stewart Bell e, rapidamente, ganharam a atenção da comunidade de mecânica quântica. Sendo uns dos tópicos mais importantes para a computação quântic
Corrigido, obrigado!

2022-09-26 20:16 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Agora se medidos a segunda propriedade, A e B, teremos 50% de chance de encontrar A e 50% de chance de encontrar B. Após medir novamante a primeira propriedade, esperariamos encontrar o primeiro valo
Corrigido, obrigado!

2022-09-26 20:16 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +O que Einstein alega no artigo é que a informação da medição de uma das particulas não pode ser transmitida mais rápida do que a luz. Ou seja, quando medidos a segunda particula não pode esperar a "l
Corrigido, obrigado!

2022-09-26 20:16 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +A partir desse artigo, físicos começaram a testar a ideia apresenta por Bell e encontrar os resultados esperados pelo seu artigo.
Corrigido, obrigado!

2022-09-26 20:16 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Assim quando mudados a propriedade medida, de alguma forma, perdemos a medição anterior.
Corrigido, obrigado!

2022-09-26 20:16 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Esse paradoxo durou até 1964 quando John Stewart Bell publicou um estudo provando que existem sistemas que não podem ser explicados por uma teoria local e com variáveis escondidadas. Nesse mesmo arti
Corrigido, obrigado!

2022-09-26 20:16 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Os 4 bell state são mostrados abaixo:
Corrigido, obrigado!

2022-09-26 20:16 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Uma vez medido uma das propriedades, digamos 0 e 1, as demais medições irão encontrar o mesmo valor, ou seja, teremos 100% de chance de enconrar o mesmo valor.
Corrigido, obrigado!

2022-09-27 09:31 UTC, qcomp-eld requested changes

2022-09-27 09:31 UTC, qcomp-eld commented on _posts/2022-09-06-bell-states.md
> +O que Einstein alega no artigo é que a informação da medição de uma das particulas não pode ser transmitida mais rápida do que a luz. Ou seja, quando medimos a segunda particula não pode esperar a "l
até ela "decidir"

2022-09-27 09:31 UTC, qcomp-eld commented on _posts/2022-09-06-bell-states.md
> +Vamos analisar o sistema 1. Nele temos duas possibilidades: primero, Alice mede seu qubit e verifica que ele colapsa para o qubit $$\ket{0}$$. Assim, ela sabe que Bob vai ter o qubit $$\ket{1}$$. Ago
50% de chances de colapsar

2022-09-27 11:35 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +O que Einstein alega no artigo é que a informação da medição de uma das particulas não pode ser transmitida mais rápida do que a luz. Ou seja, quando medimos a segunda particula não pode esperar a "l
Obrigado.

2022-09-27 11:36 UTC, alissonfumaco commented on _posts/2022-09-06-bell-states.md
> +Vamos analisar o sistema 1. Nele temos duas possibilidades: primero, Alice mede seu qubit e verifica que ele colapsa para o qubit $$\ket{0}$$. Assim, ela sabe que Bob vai ter o qubit $$\ket{1}$$. Ago
Obrigado.

2022-09-27 20:30 UTC, merged